### ISSUE TITLE
Could you please share some simulated data?

### ISSUE THREAD

**Issue by ZHANGQing163** [eloygeenjaar/normative-smri-psychopathology#1]
Dear Geenjaar,
Excuse me, I am Qing Zhang, a Ph.D. student from the Department of  Psychology, University of Chinese Academy Sciences, majoring in children's brain development.
I recently read your paper entitled "Neurodevelopmental Trajectories in Children With Internalizing, Externalizing and Emotion Dysregulation Symptoms”. I think it's a remarkable advance in characterizing longitudinal patterns of brain development using normative modeling. Thanks for your analysis scripts in ‘Github’. However,  I failed to find some fake data or simulated data. Could you please send me some simulated data? or just the variable lists of the data? It may help me a lot to learn your scripts. 
Looking forward to your reply, thank you very much! 

Best wishes,
Qing
Email: zhangqing@psych.ac.cn

**Comment by eloygeenjaar** [comment]
I have added the simulated data in the README and sent you an email!

**Comment by ZHANGQing163** [comment]
I have received your email, thank you very much!
